# Generated by Django 6.0 on 2026-01-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsricption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'permissions': [('advanced', 'advanced permissions'), ('Pro', 'Pro Permissions'), ('basic', 'basic permissions')],
            },
        ),
    ]
