# Generated by Django 6.0 on 2026-01-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'permissions': [('basic', 'Basic Perm'), ('Pro', 'Pro Perm'), ('advanced', 'Advanced Perm'), ('Enterprise', 'Enterprise Perm')],
            },
        ),
    ]
