# Generated by Django 6.0 on 2026-01-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUBSCRIPTIONS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsricption',
            options={'permissions': [('advanced', 'Advanced Permissions'), ('Pro', 'Pro Permissions'), ('basic', 'Basic Permissions'), ('Basic Ai', 'Basic Ai Perm')]},
        ),
    ]
