# Generated by Django 6.0 on 2026-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBSCRIPTIONS', '0002_alter_subsricption_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsricption',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
