# Generated by Django 6.0 on 2026-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'Pro', 'advanced', 'Enterprise'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
