# Generated by Django 6.0 on 2026-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
